language: python
python:
    - 2.7
install:
    - pip install python-coveralls
    - pip install pep8
    - pip install -r requirements.txt
script:
    - pep8 --exclude=migrations .
    - coverage run --source='.' --omit='*migrations*' ./manage.py test robo_web
after_success:
    - coveralls
